// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: m4a1. Reload authoring duration: 50 ticks (server owns timing).
uint aechronis_curve_key_m4a1() { return 4382498u; }

vec3 aechronis_authored_pivot_m4a1(int bone) {
    if (bone == 1) return vec3(7.933, 7.221, 8.074);
    if (bone == 2) return vec3(8.0, 8.0, 8.0);
    return vec3(8.0, 6.0, 12.0);
}
