// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: qbz_95. Reload authoring duration: 60 ticks (server owns timing).
uint aechronis_curve_key_qbz_95() { return 5556252u; }

vec3 aechronis_authored_pivot_qbz_95(int bone) {
    if (bone == 1) return vec3(8.0, 8.487, 11.208);
    if (bone == 2) return vec3(8.0, 8.0, 8.0);
    return vec3(8.0, 6.0, 12.0);
}
