// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: mg3. Reload authoring duration: 100 ticks (server owns timing).
uint aechronis_curve_key_mg3() { return 6404130u; }

vec3 aechronis_authored_pivot_mg3(int bone) {
    if (bone == 1) return vec3(6.836, 7.94, 9.947);
    if (bone == 2) return vec3(8.79688, 7.80062, 8.87214);
    return vec3(8.0, 6.0, 12.0);
}
