// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: g3. Reload authoring duration: 60 ticks (server owns timing).
uint aechronis_curve_key_g3() { return 15720109u; }

vec3 aechronis_authored_pivot_g3(int bone) {
    if (bone == 1) return vec3(8.0, 5.28, 7.79);
    if (bone == 2) return vec3(7.7375, 6.61, 1.75625);
    return vec3(8.0, 6.0, 12.0);
}
