// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: mp5. Reload authoring duration: 48 ticks (server owns timing).
uint aechronis_curve_key_mp5() { return 3428451u; }

vec3 aechronis_authored_pivot_mp5(int bone) {
    if (bone == 1) return vec3(8.0, 7.429, 4.216);
    if (bone == 2) return vec3(7.835, 8.4575, 0.05);
    return vec3(8.0, 6.0, 12.0);
}
