// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: at4. Reload authoring duration: 100 ticks (server owns timing).
uint aechronis_curve_key_at4() { return 5918650u; }

vec3 aechronis_authored_pivot_at4(int bone) {
    if (bone == 1) return vec3(7.825, 7.8, 9.5);
    if (bone == 2) return vec3(8.0, 8.0, 8.0);
    return vec3(8.0, 6.0, 12.0);
}
