// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: vz61. Reload authoring duration: 60 ticks (server owns timing).
uint aechronis_curve_key_vz61() { return 13628073u; }

vec3 aechronis_authored_pivot_vz61(int bone) {
    if (bone == 1) return vec3(8.195, 6.68, 6.214);
    if (bone == 2) return vec3(8.0, 8.0, 8.0);
    return vec3(8.0, 6.0, 12.0);
}
