// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: ak12. Reload authoring duration: 60 ticks (server owns timing).
uint aechronis_curve_key_ak12() { return 6190527u; }

vec3 aechronis_authored_pivot_ak12(int bone) {
    if (bone == 1) return vec3(7.981, 6.82, 7.912);
    if (bone == 2) return vec3(8.0, 8.0, 8.0);
    return vec3(8.0, 6.0, 12.0);
}
