// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: ak74. Reload authoring duration: 64 ticks (server owns timing).
uint aechronis_curve_key_ak74() { return 10194193u; }

vec3 aechronis_authored_pivot_ak74(int bone) {
    if (bone == 1) return vec3(7.825, 7.8, 8.65);
    if (bone == 2) return vec3(8.0, 8.0, 8.0);
    return vec3(8.0, 6.0, 12.0);
}
