// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: m9. Reload authoring duration: 40 ticks (server owns timing).
uint aechronis_curve_key_m9() { return 721510u; }

vec3 aechronis_authored_pivot_m9(int bone) {
    if (bone == 1) return vec3(8.225, 8.868, 11.978);
    if (bone == 2) return vec3(8.0, 8.0, 8.0);
    return vec3(8.0, 6.0, 12.0);
}
