// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: glock17. Reload authoring duration: 44 ticks (server owns timing).
uint aechronis_curve_key_glock17() { return 4601043u; }

vec3 aechronis_authored_pivot_glock17(int bone) {
    if (bone == 1) return vec3(8.02, 0.6, 12.5);
    if (bone == 2) return vec3(8.0, 8.0, 8.0);
    return vec3(8.0, 6.0, 12.0);
}
