// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: awp. Reload authoring duration: 80 ticks (server owns timing).
uint aechronis_curve_key_awp() { return 16295965u; }

vec3 aechronis_authored_pivot_awp(int bone) {
    if (bone == 1) return vec3(8.0, 5.875, 12.977);
    if (bone == 2) return vec3(8.0, 6.23125, 11.6);
    return vec3(8.0, 6.0, 12.0);
}
