// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: ak47. Reload authoring duration: 60 ticks (server owns timing).
uint aechronis_curve_key_ak47() { return 13471968u; }

vec3 aechronis_authored_pivot_ak47(int bone) {
    if (bone == 1) return vec3(7.998, 5.237, 5.716);
    if (bone == 2) return vec3(8.0, 8.0, 8.0);
    return vec3(8.0, 6.0, 12.0);
}
