// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: m1867_werndl_holub. Reload authoring duration: 68 ticks (server owns timing).
uint aechronis_curve_key_m1867_werndl_holub() { return 346670u; }

vec3 aechronis_authored_pivot_m1867_werndl_holub(int bone) {
    if (bone == 1) return vec3(8.294, 8.52343, 11.30179);
    if (bone == 2) return vec3(8.1, 8.27879, 9.39888);
    return vec3(8.0, 6.0, 12.0);
}
