// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: adams_mkiii_revolver. Reload authoring duration: 100 ticks (server owns timing).
uint aechronis_curve_key_adams_mkiii_revolver() { return 16155386u; }

vec3 aechronis_authored_pivot_adams_mkiii_revolver(int bone) {
    if (bone == 1) return vec3(8.0, 8.31, 9.87);
    if (bone == 2) return vec3(8.0, 7.9, 9.0);
    return vec3(8.0, 6.0, 12.0);
}
