// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: mauser_model_1871. Reload authoring duration: 64 ticks (server owns timing).
uint aechronis_curve_key_mauser_model_1871() { return 8074484u; }

vec3 aechronis_authored_pivot_mauser_model_1871(int bone) {
    if (bone == 1) return vec3(8.0, 8.5, 9.15);
    if (bone == 2) return vec3(8.0, 8.5, 11.185);
    return vec3(8.0, 6.0, 12.0);
}
