// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: dreyse_needle_gun. Reload authoring duration: 60 ticks (server owns timing).
uint aechronis_curve_key_dreyse_needle_gun() { return 1295425u; }

vec3 aechronis_authored_pivot_dreyse_needle_gun(int bone) {
    if (bone == 1) return vec3(8.0, 8.37879, 8.4);
    if (bone == 2) return vec3(8.0, 7.98687, 9.28282);
    return vec3(8.0, 6.0, 12.0);
}
