// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: martini_henry. Reload authoring duration: 72 ticks (server owns timing).
uint aechronis_curve_key_martini_henry() { return 15681939u; }

vec3 aechronis_authored_pivot_martini_henry(int bone) {
    if (bone == 1) return vec3(8.0, 7.00245, 10.08749);
    if (bone == 2) return vec3(7.98878, 8.72666, 10.3245);
    return vec3(8.0, 6.0, 12.0);
}
