// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: colt_1851_navy_revolver. Reload authoring duration: 120 ticks (server owns timing).
uint aechronis_curve_key_colt_1851_navy_revolver() { return 5184019u; }

vec3 aechronis_authored_pivot_colt_1851_navy_revolver(int bone) {
    if (bone == 1) return vec3(8.0, 8.3, 9.8);
    if (bone == 2) return vec3(8.0, 7.92, 8.13);
    return vec3(8.0, 6.0, 12.0);
}
