// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: enfield_pattern_1853. Reload authoring duration: 120 ticks (server owns timing).
uint aechronis_curve_key_enfield_pattern_1853() { return 489243u; }

vec3 aechronis_authored_pivot_enfield_pattern_1853(int bone) {
    if (bone == 1) return vec3(8.0, 6.94, -3.0);
    if (bone == 2) return vec3(8.85, 8.0, 12.5);
    return vec3(8.0, 6.0, 12.0);
}
