// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: winchester_model_1873. Reload authoring duration: 100 ticks (server owns timing).
uint aechronis_curve_key_winchester_model_1873() { return 8507348u; }

vec3 aechronis_authored_pivot_winchester_model_1873(int bone) {
    if (bone == 1) return vec3(8.0, 6.9, 10.5);
    if (bone == 2) return vec3(8.0, 8.8, 9.7);
    return vec3(8.0, 6.0, 12.0);
}
