// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: colt_single_action_army. Reload authoring duration: 120 ticks (server owns timing).
uint aechronis_curve_key_colt_single_action_army() { return 7040850u; }

vec3 aechronis_authored_pivot_colt_single_action_army(int bone) {
    if (bone == 1) return vec3(8.0, 8.25, 9.0);
    if (bone == 2) return vec3(8.0, 8.7, 11.4);
    return vec3(8.0, 6.0, 12.0);
}
