// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: chassepot_carbine. Reload authoring duration: 56 ticks (server owns timing).
uint aechronis_curve_key_chassepot_carbine() { return 7111896u; }

vec3 aechronis_authored_pivot_chassepot_carbine(int bone) {
    if (bone == 1) return vec3(8.0, 8.37879, 8.4);
    if (bone == 2) return vec3(8.0, 8.37879, 9.99888);
    return vec3(8.0, 6.0, 12.0);
}
