// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: coach_gun. Reload authoring duration: 80 ticks (server owns timing).
uint aechronis_curve_key_coach_gun() { return 2514555u; }

vec3 aechronis_authored_pivot_coach_gun(int bone) {
    if (bone == 1) return vec3(8.0, 8.12, 10.15);
    if (bone == 2) return vec3(8.0, 7.58, 8.6);
    return vec3(8.0, 6.0, 12.0);
}
