// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: spencer_model_1860. Reload authoring duration: 84 ticks (server owns timing).
uint aechronis_curve_key_spencer_model_1860() { return 9429535u; }

vec3 aechronis_authored_pivot_spencer_model_1860(int bone) {
    if (bone == 1) return vec3(8.0, 7.1, 9.4);
    if (bone == 2) return vec3(8.0, 8.15, 10.1);
    return vec3(8.0, 6.0, 12.0);
}
