// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: vetterli_model_1870. Reload authoring duration: 56 ticks (server owns timing).
uint aechronis_curve_key_vetterli_model_1870() { return 1503433u; }

vec3 aechronis_authored_pivot_vetterli_model_1870(int bone) {
    if (bone == 1) return vec3(8.0, 8.5, 9.15);
    if (bone == 2) return vec3(8.0, 8.5, 11.05);
    return vec3(8.0, 6.0, 12.0);
}
