// Generated by Aechronis Combat Animation for Blockbench 5+.
// Additive model-pixel / Euler XYZ degree offsets. Edit the .bbmodel source.
// Profile: berdan_ii_rifle. Reload authoring duration: 64 ticks (server owns timing).
uint aechronis_curve_key_berdan_ii_rifle() { return 4858891u; }

vec3 aechronis_authored_pivot_berdan_ii_rifle(int bone) {
    if (bone == 1) return vec3(8.0, 8.37879, 8.4);
    if (bone == 2) return vec3(8.0, 8.37879, 9.38987);
    return vec3(8.0, 6.0, 12.0);
}
